#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-simplecov-json
Version  : 0.2
Release  : 5
URL      : https://rubygems.org/downloads/simplecov-json-0.2.gem
Source0  : https://rubygems.org/downloads/simplecov-json-0.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-json
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-simplecov

%description
No detailed description available

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n simplecov-json-0.2
gem spec %{SOURCE0} -l --ruby > rubygem-simplecov-json.gemspec

%build
gem build rubygem-simplecov-json.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
simplecov-json-0.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/simplecov-json-0.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/simplecov-json-0.2/lib/simplecov-json.rb
/usr/lib64/ruby/gems/2.3.0/gems/simplecov-json-0.2/test/helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/simplecov-json-0.2/test/test_simplecov_json.rb
/usr/lib64/ruby/gems/2.3.0/specifications/simplecov-json-0.2.gemspec
