#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-simplecov-json
Version  : 0.2
Release  : 3
URL      : https://rubygems.org/downloads/simplecov-json-0.2.gem
Source0  : https://rubygems.org/downloads/simplecov-json-0.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-docile
BuildRequires : rubygem-json
BuildRequires : rubygem-metaclass
BuildRequires : rubygem-mocha
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-test-unit

%description
No detailed description available

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n simplecov-json-0.2
gem spec %{SOURCE0} -l --ruby > rubygem-simplecov-json.gemspec

%build
gem build rubygem-simplecov-json.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
simplecov-json-0.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/simplecov-json-0.2
ruby -I"lib:test" test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/simplecov-json-0.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-json-0.2/ri/SimpleCov/Formatter/JSONFormatter/cdesc-JSONFormatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-json-0.2/ri/SimpleCov/Formatter/JSONFormatter/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-json-0.2/ri/SimpleCov/Formatter/JSONFormatter/output_filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-json-0.2/ri/SimpleCov/Formatter/JSONFormatter/output_filepath-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-json-0.2/ri/SimpleCov/Formatter/JSONFormatter/output_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-json-0.2/ri/SimpleCov/Formatter/JSONFormatter/output_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-json-0.2/ri/SimpleCov/Formatter/cdesc-Formatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-json-0.2/ri/SimpleCov/cdesc-SimpleCov.ri
/usr/lib64/ruby/gems/2.2.0/doc/simplecov-json-0.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-json-0.2/coverage/coverage.json
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-json-0.2/lib/simplecov-json.rb
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-json-0.2/test/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/simplecov-json-0.2/test/test_simplecov_json.rb
/usr/lib64/ruby/gems/2.2.0/specifications/simplecov-json-0.2.gemspec
